### PR TITLE
ng-facebooc

### PR DESCRIPTION
**Pull request by Gogistics**
added ng, leaflet, and d3 modules, updated navbar, and update front page

### CODE REVIEW

**Comment by jserv** [comment]
Please squash the related commits!

**Comment by Gogistics** [comment]
sorry, forgot to do it

**Comment by jserv** [comment]
@Gogistics : You should use `git rebase -i` to rework these commits. I think there could be 3 commits:
- integrate external web frontend framework
- UI control tweaks
- style and reusable components

**Comment by Gogistics** [comment]
yes, i'm doing it.

**Comment by Gogistics** [comment]
i better start a new fork. yesterday i modified the website while working and not did it properly

**Comment by jserv** [comment]
Close per the request of @Gogistics.

**Pull request closed without merging**
