### PR TITLE
ng-facebooc on linode

### PR DESCRIPTION
**Pull request by Gogistics**
add web front-end frameworks, make navbar responsive, add js paths to footer.html, create main.js and add ng-app, update header.html and index.html

### CODE REVIEW

**Comment by jserv** [comment]
@Gogistics : You should split the changes into several functional commits as I mentioned before.
Also, what is "ng-facebooc"? Can you write down meaningful words?

**Comment by jserv** [comment]
Instead of copying full angular-1.5.5 release, can you provide the minimal parts required by further modifications?

**Comment by Gogistics** [comment]
Q-1.
ng is the common abbreviation of angularjs. sure, i can change it to angularjs

Q-2.
sure, no problem. i'll do it today

**Comment by Gogistics** [comment]
btw, do you need me to just include the minified files of bootstrap, d3, jq_plugin, leaflet-0.7, and timbre for further use?

**Comment by jserv** [comment]
Exactly, we should always ensure minimal dependency of external resources as possible.

**Comment by Gogistics** [comment]
Got it.

Question, is there a protocol to follow to make a commit and the corresponding comment? Sorry, originally I wanted my intern to integrate the website with Angular.js, D3, and Leaflet frameworks as a practice, and I didn’t watch what he was doing. Now I’m going to take care of it myself.

For example: I usually control projects by JIRA. When teammates want to solve issues, bugs, or do something else, we create tickets and write down a description. Say I want to integrate Facebooc website with Angular.js. Then, the person who is going to do the work will include the required .js and .css files, set the scripts’ path, and bootstrap the structure of Angular.js application. Once everything is done and the changes have to be pushed to the remote repository, this person would probably execute the following commands (FACEBOOC-1 is the ticket ID created by JIRA):
$ git add .
$ git commit –m “FACEBOOC-1: integrate the website with ng framework, include the required .js and .css files, set the scripts’ path, and bootstrap the structure of Angular.js application”
$ git push

Thank you.

**Comment by jserv** [comment]
@Gogistics : I don't fully understand what you intended to ask yet. You can look at the documentations via GitHub website:
- https://help.github.com/articles/using-pull-requests/
- https://developer.github.com/guides/working-with-comments/

**Pull request closed without merging**
