### PR TITLE
Change post style and add ability of line wrap

### PR DESCRIPTION
**Pull request by oiz5201618**

### CODE REVIEW

**Comment by jserv** [comment]
Fix English syntax.

**Comment by jserv** [comment]
Did you mean the ability of line wrap?

**Comment by oiz5201618** [comment]
Yes!!! I'm confused about the word which express the line wrap.

**Comment by oiz5201618** [comment]
Fix right now!

**Comment by oiz5201618** [comment]
Teacher, I have some question.
Once I pull a request, can I pull another new request?
Because I push new commit, the old request will be updated.
If can't, my request stuck here. Does it mean I should close the request? or wait the request be checked?
Sorry for my studip question, I'm new for collaboration.

**Comment by jserv** [comment]
No, use `git commit --amend` to rework your comments and code. Then, use `git push --force` to update.

**Comment by oiz5201618** [comment]
But the command **git commit --amend** modify the latest commit, it will flush the old commit.
I want to pull another new function, should I give up the old request?

**Comment by jserv** [comment]
Use `git rebase -i` to rework! Please read: https://github.com/doggy8088/Learn-Git-in-30-days

**Comment by jserv** [comment]
@oiz5201618 : Did you push the revised commit?

**Comment by oiz5201618** [comment]
@jserv  I already push the revised version.

**Comment by jserv** [comment]
Fix the syntax error in Git commit messages.

**Comment by oiz5201618** [comment]
Teacher, I have fixed it yet.

**Pull request merged**
