### PR TITLE
Change post html tag

### PR DESCRIPTION
**Pull request by oiz5201618**
change post html tag to make the line feed. If the text is more than range of textarea, it'll make a scroll.

### CODE REVIEW

**Comment by jserv** [comment]
@oiz5201618 : Please read the article and rework your patch: http://chris.beams.io/posts/git-commit/

**Comment by oiz5201618** [comment]
OK, I study right now.

**Comment by oiz5201618** [comment]
I want to ask some question. The article suggested that I should make a brief commit, but if the function or benefit cannot briefly introduce by commit, how should I do. Should I mention more detail at the comment of comment?

**Comment by jserv** [comment]
@oiz5201618 : You have to improve your expression skills.

**Comment by oiz5201618** [comment]
I will do my best to improve it !

**Pull request closed without merging**
