### PR TITLE
add malloc() && realloc() success check for bs.c

### PR DESCRIPTION
**Pull request by WithGJR**

### CODE REVIEW

**Comment by WithGJR** [comment]
剛剛也修正了 navbar 的 bug

**Comment by jserv** [comment]
Please read this article: http://fred-zone.blogspot.tw/2015/09/git-fork.html

**Comment by WithGJR** [comment]
我都有 git pull 這個 repo 最新的 commit 之後再合併自己更動的 code

還是我漏掉了什麼？

**Comment by jserv** [comment]
Instead of using `git merge`, you must use `git rebase`!

**Comment by jserv** [comment]
If `git rebase` is successfully performed, there is no commit like "Merge branch 'develop'".

**Comment by jserv** [comment]
Also, the commit "fix navbar bug: make dashboard" is not related to this pull request, and you have to submit another PR.

**Comment by jserv** [comment]
So, first, you should create a new GIT branch and rework. Then, use `git push --force` to replace the existing commits.

**Comment by jserv** [comment]
Ensure yourself read the article before sending pull request!
- [How to Rebase a Pull Request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

**Comment by WithGJR** [comment]
謝謝 學到一課了

剛剛把commit調整好了，再麻煩您看一下，感謝

**Comment by WithGJR** [comment]
剛剛想到應該只有 bs.c 用 assert 檢查不會有問題，其他部分用 assert 假設真的遇到記憶體分配失敗的話，程式會直接結束

**Comment by jserv** [comment]
Ideally, [memory pool](https://en.wikipedia.org/wiki/Memory_pool) is always used for long-term operations rather than frequent `malloc()` and `free()`.

**Comment by WithGJR** [comment]
那麼我明天先把它改成只有 bs.c 加上 assert 的檢查，這個 PR 就先以這個檔案為主。 memory pool 我再研究看看，如果有能力再看看能不能幫忙加上去。

不懂的東西真的好多啊

**Comment by WithGJR** [comment]
改好了

**Comment by jserv** [comment]
@WithGJR : Thanks for your contribution.

**Pull request merged**
